on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "src/**"
name: Publish Geensnor
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/*"
      - name: Checkout your repository using git
        uses: actions/checkout@v6
      - name: Install, build, and upload your site output
        uses: withastro/action@v6
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@v4.3.6
        with:
          server: ${{ secrets.ftpserver }}
          username: ${{ secrets.ftpusername }}
          password: ${{ secrets.ftppassword }}
          dangerous-clean-slate: false
          local-dir: ./dist/
          timeout: 60000
