name: YouTube no cookie find and replace
on: [push, pull_request]
jobs:
  yt-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Find and Replace www.youtube.com
        uses: jacobtomlinson/gha-find-replace@v3
        with:
          find: "https://www.youtube.com"
          replace: "https://www.youtube-nocookie.com"
          include: "_posts/**"
          regex: true
      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
      - uses: EndBug/add-and-commit@v9
